# Generated by Django 3.1.7 on 2021-03-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=14)),
                ('fantasia', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('iniciodecontrato', models.CharField(max_length=20)),
                ('vigenciadecontrato', models.CharField(max_length=20)),
                ('modalidade', models.CharField(choices=[('assessoria', 'Assessoria'), ('consultoria', 'Consultoria'), ('assessoria e consultoria', 'Assessoria e Consultoria')], default='assessoria', max_length=25)),
                ('area', models.TextField(null=True)),
                ('normas', models.TextField(null=True)),
            ],
        ),
    ]
